before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - id: "fdnssearch"
    main: ./cmd/fdnssearch/main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/nscuro/fdnssearch/internal/version.Version={{ .Version }}
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64

archives:
  - replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      amd64: x86_64

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - '^Merge '